// <auto-generated />
using System;
using Infaestructure.Persistence.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infaestructure.Migrations
{
    [DbContext(typeof(RestauranteBD))]
    [Migration("20230425203432_createRestauranteBD")]
    partial class createRestauranteBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Property<Guid>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaEntregaId")
                        .HasColumnType("int");

                    b.Property<int>("PrecioTotal")
                        .HasColumnType("int");

                    b.HasKey("ComandaId");

                    b.HasIndex("FormaEntregaId");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.Property<int>("ComandaMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComandaMercaderiaId"));

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("ComandaMercaderiaId");

                    b.HasIndex("ComandaId");

                    b.HasIndex("MercaderiaId");

                    b.ToTable("ComandaMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Property<int>("FormaEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaEntregaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FormaEntregaId");

                    b.ToTable("FormasEntrega");

                    b.HasData(
                        new
                        {
                            FormaEntregaId = 1,
                            Descripcion = "Salón"
                        },
                        new
                        {
                            FormaEntregaId = 2,
                            Descripcion = "PedidosYa"
                        },
                        new
                        {
                            FormaEntregaId = 3,
                            Descripcion = "Delivery"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Property<int>("MercaderiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MercaderiaID"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Preparacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoMercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("MercaderiaID");

                    b.HasIndex("TipoMercaderiaId");

                    b.ToTable("Mercaderia");

                    b.HasData(
                        new
                        {
                            MercaderiaID = 1,
                            Imagen = "https://imagesvc.meredithcorp.io/v3/mm/image?q=60&c=sc&poi=face&w=2000&h=1000&url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F21%2F2018%2F02%2F14%2Frecetas-4115-spaghetti-boloesa-facil-2000.jpg",
                            Ingredientes = "Spaghettis de harina,salsa fileto, carne",
                            Nombre = "Spaghettis",
                            Precio = 1000,
                            Preparacion = "Se ponen los fideos a hervir en una olla y luego se cubre con la salsa bolognesa",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaID = 2,
                            Imagen = "https://www.laitalianapastas.com/wp-content/uploads/2017/05/noquispapa.jpg",
                            Ingredientes = "Ñoquis de papa,salsa fileto, carne",
                            Nombre = "Ñoquis",
                            Precio = 1000,
                            Preparacion = "Se ponen los ñoquis a hervir en una olla y luego se cubre con la salsa bolognesa",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaID = 3,
                            Imagen = "https://www.clarin.com/img/2021/12/15/la-milanesa-con-papas-fritas___OFsTMm3-P_2000x1500__1.jpg",
                            Ingredientes = "Milanesa de carne, papas",
                            Nombre = "Milanesa de carne",
                            Precio = 1200,
                            Preparacion = "Se ponen en el horno las milanesas y luego las papas para salir bien doraditas",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaID = 4,
                            Imagen = "https://i.ytimg.com/vi/OP74S9ffEyo/maxresdefault.jpg",
                            Ingredientes = "Milanesa de pollo, papas",
                            Nombre = "Milanesa de pollo",
                            Precio = 1200,
                            Preparacion = "Se ponen en el horno las milanesas y luego las papas para salir bien doraditas",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaID = 5,
                            Imagen = "https://www.clarin.com/img/2020/07/21/EVsX1RphU_1200x630__1.jpg",
                            Ingredientes = "muzarella,rebozado de pan rallado",
                            Nombre = "Bastones de muzzarella",
                            Precio = 700,
                            Preparacion = "Se rebozan muzarella en pan rallado y se ponen en la freidora para que salgan crocantes",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaID = 6,
                            Imagen = "https://www.petitchef.es/imgupl/recipe-step/460076s2122991.jpg",
                            Ingredientes = "Papas fritas",
                            Nombre = "Papas fritas",
                            Precio = 600,
                            Preparacion = "Se ponen las papas fritas en la freidora para que salgan lo más doradas posibles",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaID = 7,
                            Imagen = "https://habemusasado.com.ar/wp-content/uploads/2021/03/lomo-a-la-parrilla-con-papas-a-la-provenzal.jpg",
                            Ingredientes = "Lomo",
                            Nombre = "Lomo",
                            Precio = 2500,
                            Preparacion = "Se pone el lomo en la parrilla hasta que quedé lo más jugoso posible",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaID = 8,
                            Imagen = "https://hacerasado.com.ar/wp-content/uploads/2020/05/vacio-asado.jpg",
                            Ingredientes = "Vacío",
                            Nombre = "Vacío",
                            Precio = 2000,
                            Preparacion = "Se pone el lomo en la parrilla hasta que quedé lo más jugoso posible del chef",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaID = 9,
                            Imagen = "https://irecetasfaciles.com/wp-content/uploads/2019/08/pizza-de-jamon-queso-y-tocino.jpg",
                            Ingredientes = "Harina, Salsa de tomate, tomate, queso, aceitunas",
                            Nombre = "Pizza de muzarella",
                            Precio = 1700,
                            Preparacion = "Se amaza la masa, se le coloca muzzarela, el tomate y luego se manda al horno hasta que esté cocida",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaID = 10,
                            Imagen = "https://www.johaprato.com/files/styles/flexslider_full/public/pizza-napolitana.jpg?itok=N0LPyO1C",
                            Ingredientes = "Harina, Salsa de tomate, tomate, queso, jamón, aceitunas",
                            Nombre = "Pizza napolitana",
                            Precio = 1900,
                            Preparacion = "Se amaza la masa, se le coloca muzzarela, el tomate y luego se manda al horno hasta que esté cocida",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaID = 11,
                            Imagen = "https://deliveryolavarria.com/wp-content/uploads/classified-listing/2021/06/Sandwich-de-Milanesa-Completo-Rotiseria-Lanueva-Delivery-Olavarria.jpg",
                            Ingredientes = "Pan, milanesa de pollo/carne, lechuga, tomate, queso, jamón",
                            Nombre = "Sandwich de milanesa",
                            Precio = 1500,
                            Preparacion = "Se coloca la milanesa entre dos panes y luego se coloca tomate, lechuga, jamon y queso",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaID = 12,
                            Imagen = "https://laverdadonline.com/wp-content/uploads/2021/06/lomito-1280x720.jpg",
                            Ingredientes = "Pan, lomo, lechuga, tomate, queso, jamón",
                            Nombre = "Sandwich de lomo",
                            Precio = 2500,
                            Preparacion = "Se coloca el lomo entre dos panes y luego se coloca tomate, lechuga, jamon y queso",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaID = 13,
                            Imagen = "https://media.minutouno.com/p/47b326b7fd5e666efcda98c58264ef19/adjuntos/150/imagenes/037/428/0037428131/610x0/smart/jardinera-retirada-anmat.jpg",
                            Ingredientes = "papa, zanahoria, arvejas, zapallo",
                            Nombre = "Ensalada jardinera",
                            Precio = 1000,
                            Preparacion = "Se coloca papa, zanahoria, arvejas y el zapallo y se mezclan",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaID = 14,
                            Imagen = "https://recetas123.net/wp-content/uploads/Ensalada-rusa.jpg",
                            Ingredientes = "papa, mayonesa, arvejas",
                            Nombre = "Ensalada rusa",
                            Precio = 1000,
                            Preparacion = "Se coloca papa, mayonesa, arvejas y se mezcla",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaID = 15,
                            Imagen = "https://http2.mlstatic.com/D_NQ_NP_940822-MLA31035814287_062019-O.webp",
                            Ingredientes = "Coca cola",
                            Nombre = "Coca Cola",
                            Precio = 350,
                            Preparacion = "Se sirve en un vaso coca cola",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaID = 16,
                            Imagen = "https://images.ecestaticos.com/hGWahS40nsMxN3rj5xvDbv2689I=/118x0:2004x1413/1200x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F2d3%2F829%2Fca8%2F2d3829ca834316ffe100eb7277eb0d29.jpg",
                            Ingredientes = "Agua",
                            Nombre = "Agua",
                            Precio = 350,
                            Preparacion = "Se sirve en un vaso agua",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaID = 17,
                            Imagen = "https://thumbs.dreamstime.com/b/vaso-de-cerveza-negra-aislado-sobre-fondo-blanco-contiene-trazado-recorte-marr%C3%B3n-212794983.jpg",
                            Ingredientes = "Cerveza negra",
                            Nombre = "Cerveza negra",
                            Precio = 350,
                            Preparacion = "Se sirve en un vaso cerveza negra",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaID = 18,
                            Imagen = "https://www.seekpng.com/png/detail/239-2397428_descripcin-vaso-de-cerveza-rubia.png",
                            Ingredientes = "Cerveza rubia",
                            Nombre = "Cerveza rubia",
                            Precio = 350,
                            Preparacion = "Se sirve en un vaso cerveza rubia",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaID = 19,
                            Imagen = "https://www.lactaidenespanol.com/sites/lactaid_us/files/recipe-images/easy_flan2.jpg",
                            Ingredientes = "Huevo, leche, azúcar",
                            Nombre = "Flan",
                            Precio = 800,
                            Preparacion = "mezcla el huevo con caramelo y se manda al horno en una flanera",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaID = 20,
                            Imagen = "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/301/446/products/129-tamano-web1-2b57be5f700bad859115982923788478-640-0.jpg",
                            Ingredientes = "Helado",
                            Nombre = "Helado",
                            Precio = 800,
                            Preparacion = "Se sirven bochas de helado comprado en un boul",
                            TipoMercaderiaId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Property<int>("TipoMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMercaderiaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoMercaderiaId");

                    b.ToTable("TipoMercaderia");

                    b.HasData(
                        new
                        {
                            TipoMercaderiaId = 1,
                            Descripcion = "Pastas"
                        },
                        new
                        {
                            TipoMercaderiaId = 2,
                            Descripcion = "Minutas"
                        },
                        new
                        {
                            TipoMercaderiaId = 3,
                            Descripcion = "Entradas"
                        },
                        new
                        {
                            TipoMercaderiaId = 4,
                            Descripcion = "Parrilla"
                        },
                        new
                        {
                            TipoMercaderiaId = 5,
                            Descripcion = "Pizzas"
                        },
                        new
                        {
                            TipoMercaderiaId = 6,
                            Descripcion = "Sandwich"
                        },
                        new
                        {
                            TipoMercaderiaId = 7,
                            Descripcion = "Ensalada"
                        },
                        new
                        {
                            TipoMercaderiaId = 8,
                            Descripcion = "Bebidas"
                        },
                        new
                        {
                            TipoMercaderiaId = 9,
                            Descripcion = "Cerveza artesanal"
                        },
                        new
                        {
                            TipoMercaderiaId = 10,
                            Descripcion = "Postres"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.HasOne("Domain.Entities.FormaEntrega", "FormaEntrega")
                        .WithMany("Comandas")
                        .HasForeignKey("FormaEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaEntrega");
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.HasOne("Domain.Entities.Comanda", "Comanda")
                        .WithMany("ComandasMercaderia")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mercaderia", "Mercaderia")
                        .WithMany("ComandasMercaderia")
                        .HasForeignKey("MercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Mercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.HasOne("Domain.Entities.TipoMercaderia", "TipoMercaderia")
                        .WithMany("Mercaderias")
                        .HasForeignKey("TipoMercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Navigation("ComandasMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Navigation("ComandasMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Navigation("Mercaderias");
                });
#pragma warning restore 612, 618
        }
    }
}
